# Generated by Django 3.2.2 on 2021-06-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='msg_id',
            field=models.IntegerField(default=892),
        ),
    ]
